export const GET_ARTIST_START = 'app/Artit/GET_ARTIST_START';
export const GET_ARTIST_SUCCESS = 'app/Artit/GET_ARTIST_SUCCESS';
export const GET_ARTIST_FAILURE = 'app/Artit/GET_ARTIST_FAILURE';

export const GET_ARTIST_TRACKS_START = 'app/Artit/GET_ARTIST_TRACKS_START';
export const GET_ARTIST_TRACKS_SUCCESS = 'app/Artit/GET_ARTIST_TRACKS_SUCCESS';
export const GET_ARTIST_TRACKS_FAILURE = 'app/Artit/GET_ARTIST_TRACKS_FAILURE';

export const GET_ARTIST_ALBUMS_START = 'app/Artit/GET_ARTIST_ALBUMS_START';
export const GET_ARTIST_ALBUMS_SUCCESS = 'app/Artit/GET_ARTIST_ALBUMS_SUCCESS';
export const GET_ARTIST_ALBUMS_FAILURE = 'app/Artit/GET_ARTIST_ALBUMS_FAILURE';

export const GET_ARTIST_RELATED_START = 'app/Artit/GET_ARTIST_RELATED_START';
export const GET_ARTIST_RELATED_SUCCESS =
  'app/Artit/GET_ARTIST_RELATED_SUCCESS';
export const GET_ARTIST_RELATED_FAILURE =
  'app/Artit/GET_ARTIST_RELATED_FAILURE';
