export const GET_ARTIST_START = 'app/Artist/GET_ARTIST_START';
export const GET_ARTIST_SUCCESS = 'app/Artist/GET_ARTIST_SUCCESS';
export const GET_ARTIST_FAILURE = 'app/Artist/GET_ARTIST_FAILURE';

export const GET_ARTIST_TRACKS_START = 'app/Artist/GET_ARTIST_TRACKS_START';
export const GET_ARTIST_TRACKS_SUCCESS = 'app/Artist/GET_ARTIST_TRACKS_SUCCESS';
export const GET_ARTIST_TRACKS_FAILURE = 'app/Artist/GET_ARTIST_TRACKS_FAILURE';

export const GET_ARTIST_ALBUMS_START = 'app/Artist/GET_ARTIST_ALBUMS_START';
export const GET_ARTIST_ALBUMS_SUCCESS = 'app/Artist/GET_ARTIST_ALBUMS_SUCCESS';
export const GET_ARTIST_ALBUMS_FAILURE = 'app/Artist/GET_ARTIST_ALBUMS_FAILURE';

export const GET_ARTIST_RELATED_START = 'app/Artist/GET_ARTIST_RELATED_START';
export const GET_ARTIST_RELATED_SUCCESS =
  'app/Artist/GET_ARTIST_RELATED_SUCCESS';
export const GET_ARTIST_RELATED_FAILURE =
  'app/Artist/GET_ARTIST_RELATED_FAILURE';

export const FOLLOW_ARTIST_START = 'app/Artist/FOLLOW_ARTIST_START';
export const FOLLOW_ARTIST_SUCCESS = 'app/Artist/FOLLOW_ARTIST_SUCCESS';
export const FOLLOW_ARTIST_FAILURE = 'app/Artist/FOLLOW_ARTIST_FAILURE';

export const IS_USER_FOLLOWING_START = 'app/Artist/IS_USER_FOLLOWING_START';
export const IS_USER_FOLLOWING_SUCCESS = 'app/Artist/IS_USER_FOLLOWING_SUCCESS';
export const IS_USER_FOLLOWING_FAILURE = 'app/Artist/IS_USER_FOLLOWING_FAILURE';
