export const GET_USER_PLAYLISTS_START =
  'app/Playlists/GET_USER_PLAYLISTS_START';
export const GET_USER_PLAYLISTS_SUCCESS =
  'app/Playlists/GET_USER_PLAYLISTS_SUCCESS';
export const GET_USER_PLAYLISTS_FAILURE =
  'app/Playlists/GET_USER_PLAYLISTS_FAILURE';

export const GET_PLAYLIST_START = 'app/Playlists/GET_PLAYLIST_START';
export const GET_PLAYLIST_SUCCESS = 'app/Playlists/GET_PLAYLIST_SUCCESS';
export const GET_PLAYLIST_FAILURE = 'app/Playlists/GET_PLAYLIST_FAILURE';

export const GET_USER_TRACKS_START = 'app/Playlists/GET_USER_TRACKS_START';
export const GET_USER_TRACKS_SUCCESS = 'app/Playlists/GET_USER_TRACKS_SUCCESS';
export const GET_USER_TRACKS_FAILURE = 'app/Playlists/GET_USER_TRACKS_FAILURE';

export const CREATE_PLAYLIST_START = 'app/Playlists/CREATE_PLAYLIST_START';
export const CREATE_PLAYLIST_SUCCESS = 'app/Playlists/CREATE_PLAYLIST_SUCCESS';
export const CREATE_PLAYLIST_FAILURE = 'app/Playlists/CREATE_PLAYLIST_FAILURE';

export const GET_RANDOM_TRACKS_START = 'app/Playlists/GET_RANDOM_TRACKS_START';
export const GET_RANDOM_TRACKS_SUCCESS =
  'app/Playlists/GET_RANDOM_TRACKS_SUCCESS';
export const GET_RANDOM_TRACKS_FAILURE =
  'app/Playlists/GET_RANDOM_TRACKS_FAILURE';

export const ADD_TRACK_TO_PLAYLIST_START =
  'app/Playlists/ADD_TRACK_TO_PLAYLIST_START';
export const ADD_TRACK_TO_PLAYLIST_SUCCESS =
  'app/Playlists/ADD_TRACK_TO_PLAYLIST_SUCCESS';
export const ADD_TRACK_TO_PLAYLIST_FAILURE =
  'app/Playlists/ADD_TRACK_TO_PLAYLIST_FAILURE';

export const CHECK_USER_FOLLOW_PLAYLIST_START =
  'app/Playlists/CHECK_USER_FOLLOW_PLAYLIST_START';
export const CHECK_USER_FOLLOW_PLAYLIST_SUCCESS =
  'app/Playlists/CHECK_USER_FOLLOW_PLAYLIST_SUCCESS';
export const CHECK_USER_FOLLOW_PLAYLIST_FAILURE =
  'app/Playlists/CHECK_USER_FOLLOW_PLAYLIST_FAILURE';

export const FOLLOW_PLAYLIST_START = 'app/Playlists/FOLLOW_PLAYLIST_START';
export const FOLLOW_PLAYLIST_SUCCESS = 'app/Playlists/FOLLOW_PLAYLIST_SUCCESS';
export const FOLLOW_PLAYLIST_FAILURE = 'app/Playlists/FOLLOW_PLAYLIST_FAILURE';

export const LIKE_SONG_START = 'app/Playlists/LIKE_SONG_START';
export const LIKE_SONG_FAILURE = 'app/Playlists/LIKE_SONG_FAILURE';

export const CHECK_LIKE_SONG_START = 'app/Playlists/CHECK_LIKE_SONG_START';
export const CHECK_LIKE_SONG_SUCCESS = 'app/Playlists/CHECK_LIKE_SONG_SUCCESS';
export const CHECK_LIKE_SONG_FAILURE = 'app/Playlists/CHECK_LIKE_SONG_FAILURE';

export const CLEAN_PLAYLIST = 'app/Playlists/CLEAN_PLAYLIST';
