export const GET_USER_PLAYLISTS_START =
  'app/Playlists/GET_USER_PLAYLISTS_START';
export const GET_USER_PLAYLISTS_SUCCESS =
  'app/Playlists/GET_USER_PLAYLISTS_SUCCESS';
export const GET_USER_PLAYLISTS_FAILURE =
  'app/Playlists/GET_USER_PLAYLISTS_FAILURE';

export const GET_PLAYLIST_TRACKS_START =
  'app/Playlists/GET_PLAYLIST_TRACKS_START';
export const GET_PLAYLIST_TRACKS_SUCCESS =
  'app/Playlists/GET_PLAYLIST_TRACKS_SUCCESS';
export const GET_PLAYLIST_TRACKS_FAILURE =
  'app/Playlists/GET_PLAYLIST_TRACKS_FAILURE';
