export const GET_USER_START = 'app/User/GET_USER_START';
export const GET_USER_SUCCESS = 'app/User/GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'app/User/GET_USER_FAILURE';

export const GET_USER_PLAYLISTS_START = 'app/User/GET_USER_PLAYLISTS_START';
export const GET_USER_PLAYLISTS_SUCCESS = 'app/User/GET_USER_PLAYLISTS_SUCCESS';
export const GET_USER_PLAYLISTS_FAILURE = 'app/User/GET_USER_PLAYLISTS_FAILURE';
