export const GET_SEARCH_START = 'app/Search/GET_SEARCH_START';
export const GET_SEARCH_SUCCESS = 'app/Search/GET_SEARCH_SUCCESS';
export const GET_SEARCH_FAILURE = 'app/Search/GET_SEARCH_FAILURE';

export const GET_ARTIST_SONGS_START = 'app/Search/GET_ARTIST_SONGS_START';
export const GET_ARTIST_SONGS_SUCCESS = 'app/Search/GET_ARTIST_SONGS_SUCCESS';
export const GET_ARTIST_SONGS_FAILURE = 'app/Search/GET_ARTIST_SONGS_FAILURE';

export const GET_ARTIST_ALBUMS_START = 'app/Search/GET_ARTIST_ALBUMS_START';
export const GET_ARTIST_ALBUMS_SUCCESS = 'app/Search/GET_ARTIST_ALBUMS_SUCCESS';
export const GET_ARTIST_ALBUMS_FAILURE = 'app/Search/GET_ARTIST_ALBUMS_FAILURE';

export const GET_RELATED_ARTISTS_START = 'app/Search/GET_RELATED_ARTISTS_START';
export const GET_RELATED_ARTISTS_SUCCESS =
  'app/Search/GET_RELATED_ARTISTS_SUCCESS';
export const GET_RELATED_ARTISTS_FAILURE =
  'app/Search/GET_RELATED_ARTISTS_FAILURE';

export const SET_SEARCH_VALUE = 'app/Search/SET_SEARCH_VALUE';
