export const GET_RECENTLY_PLAYED_START =
  'app/Dashboard/GET_RECENTLY_PLAYED_START';
export const GET_RECENTLY_PLAYED_SUCCESS =
  'app/Dashboard/GET_RECENTLY_PLAYED_SUCCESS';
export const GET_RECENTLY_PLAYED_FAILURE =
  'app/Dashboard/GET_RECENTLY_PLAYED_FAILURE';

export const GET_RECOMMENDATIONS_START =
  'app/Dashboard/GET_RECOMMENDATIONS_START';
export const GET_RECOMMENDATIONS_SUCCESS =
  'app/Dashboard/GET_RECOMMENDATIONS_SUCCESS';
export const GET_RECOMMENDATIONS_FAILURE =
  'app/Dashboard/GET_RECOMMENDATIONS_FAILURE';

export const GET_FEATURED_PLAYLISTS_START =
  'app/Dashboard/GET_FEATURED_PLAYLISTS_START';
export const GET_FEATURED_PLAYLISTS_SUCCESS =
  'app/Dashboard/GET_FEATURED_PLAYLISTS_SUCCESS';
export const GET_FEATURED_PLAYLISTS_FAILURE =
  'app/Dashboard/GET_FEATURED_PLAYLISTS_FAILURE';

export const GET_NEW_RELEASES_START = 'app/Dashboard/GET_NEW_RELEASES_START';
export const GET_NEW_RELEASES_SUCCESS =
  'app/Dashboard/GET_NEW_RELEASES_SUCCESS';
export const GET_NEW_RELEASES_FAILURE =
  'app/Dashboard/GET_NEW_RELEASES_FAILURE';
